### ISSUE TITLE
Could you please update hw7 before the midterm?

### ISSUE THREAD

**Issue by DirtyDrake666** [FiddieMath/FiddieMath.github.io#14]
As stated in the title

**Comment by FiddieMath** [comment]
Sure. Will be updated by Wednesday.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 04/23/2024 00:21 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [FiddieMath/FiddieMath.github.io] Could you please update hw7 before the midterm? (Issue #14) |

As stated in the title
